### ISSUE TITLE
Error - hashes don't match

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#525] opened 2020-06-29 14:17 UTC
```
PS C:\Users\Bob Turner\Documents\simple_network_sim> python -m simple_network_sim.sampleUseOfModel random
[2020-06-29 15:17:06,339] [simple_network_sim.__main__] [INFO] Parameters
        age_groups=['[17,70)']
        cmd=random
        data_pipeline_config=config.yaml
        debug=False
        infected=100
        logfile=None
        quiet=False
        regions=1
        time=200
        trials=100
        use_movement_multipliers=False
Traceback (most recent call last):
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bob Turner\Documents\simple_network_sim\simple_network_sim\sampleUseOfModel.py", line 259, in <module>
    main(sys.argv[1:])
  File "C:\Users\Bob Turner\Documents\simple_network_sim\simple_network_sim\sampleUseOfModel.py", line 28, in main
    store.read_table("human/compartment-transition"),
  File "C:\Users\Bob Turner\Documents\simple_network_sim\simple_network_sim\data.py", line 9, in read_table
    with TextIOWrapper(self.open_for_read(data_product=data_product, extension="csv")) as csv_file:
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\site-packages\data_pipeline_api\file_api.py", line 116, in open_for_read   
    verify_hash=self.fail_on_hash_mismatch,
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\site-packages\data_pipeline_api\file_api.py", line 86, in _record_access   
    ).format(**access_metadata)
ValueError: calculated hash f5c9031eef898b7ba3e21b7aa6f558aec5f8c9ea != verified hash 839721a1703f2488c029a8d3cd1a5870e433b149
PS C:\Users\Bob Turner\Documents\simple_network_sim>
```

**Comment by bobturneruk** [comment] 2020-06-29 14:18
I'll have a bit of a look at this.

**Comment by bobturneruk** [comment] 2020-06-29 14:33
Windows specific?

**Comment by aflag** [comment] 2020-06-30 16:39
I think this only happens on windows

**Comment by bobturneruk** [comment] 2020-07-07 10:37
This command now prompts the error:

```
python -m simple_network_sim.sampleUseOfModel
```

**Comment by bobturneruk** [comment] 2020-07-07 10:59
Not sure why we're seeing this on "manual" command line runs but not in automated testing...

**Comment by FiodorG** [comment] 2020-07-08 08:45
I also have this issue (on Windows 10), for now I've deactivated the hash checking

**Comment by WPettersson** [comment] 2020-07-08 08:49
Could either of you that see this error upload the two files that are being hashed somewhere, so we can inspect them? I can't imagine what difference would be present between the two, but maybe it's something we can detect and ignore/fix.

**Comment by bobturneruk** [comment] 2020-07-08 09:54
I'll look into that if @FiodorG doesn't beat me to it. I think the command should be equivalent to one of the tests, all of which pass if temp files are deleted. This is further confusing.

**Comment by FiodorG** [comment] 2020-07-08 12:08
Not sure what's the best place to share this, but I see the hashcheck faiing on every file load from store. So I picked the simplest file, here's a snippet to show what I get out of this file:
![image](https://user-images.githubusercontent.com/24376790/86916815-10017f00-c11c-11ea-8030-b1fc0badb02b.png)

**Comment by WPettersson** [comment] 2020-07-08 12:33
Thanks, that's enough :) The problem is the line endings, as I expected. However, the problem comes from the fact that git tries to be "smart" with text files, so it automatically adjusts line endings based on the OS you use.

I've pushed a draft PR to fix this to https://github.com/ScottishCovidResponse/simple_network_sim/pull/87 so if one of you can test this to see if it fixes things, that would be great. I don't know if it will immediately fix it, though, it might need more tweaking. I cannot really test as I don't have access to a Windows machine.

**Comment by bobturneruk** [comment] 2020-07-08 12:59
Sadly:
```
PS C:\Users\Bob Turner\Documents\simple_network_sim> python -m simple_network_sim.sampleUseOfModel
[2020-07-08 13:58:42,968] [simple_network_sim.__main__] [INFO] Parameters
        data_pipeline_config=config.yaml
        debug=False
        logfile=None
        quiet=False
        time=200
        use_movement_multipliers=False
Traceback (most recent call last):
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bob Turner\Documents\simple_network_sim\simple_network_sim\sampleUseOfModel.py", line 209, in <module>
    main(sys.argv[1:])
  File "C:\Users\Bob Turner\Documents\simple_network_sim\simple_network_sim\sampleUseOfModel.py", line 28, in main
    store.read_table("human/compartment-transition"),
  File "C:\Users\Bob Turner\Documents\simple_network_sim\simple_network_sim\data.py", line 9, in read_table
    with TextIOWrapper(self.open_for_read(data_product=data_product, extension="csv")) as csv_file:
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\site-packages\data_pipeline_api\file_api.py", line 122, in open_for_read
    verify_hash=self.fail_on_hash_mismatch,
  File "C:\Users\Bob Turner\.conda\envs\simple_network_sim\lib\site-packages\data_pipeline_api\file_api.py", line 93, in _record_access
    ).format(**access_metadata)
ValueError: calculated hash f5c9031eef898b7ba3e21b7aa6f558aec5f8c9ea != verified hash 839721a1703f2488c029a8d3cd1a5870e433b149
PS C:\Users\Bob Turner\Documents\simple_network_sim>
```

**Comment by bobturneruk** [comment] 2020-07-08 13:01
Thanks for your efforts on this @WPettersson. This would be a route to testing on Windows 10 - it's pretty easy but there's a lot to download! https://app.vagrantup.com/gusztavvargadr/boxes/windows-10

**Comment by WPettersson** [comment] 2020-07-08 16:35
Ok, I have a few things I've noticed after building such a virtual machine.
1) To get your own repository to store the CSV files using the Unix-based line endings, you need to rebuild the files by running the following _after_ merging my change. Note that this will destroy any work you have not yet committed, so be careful:

```
git rm --cached -r .
git reset --hard
```

Once you have checked out my branch, and run the above two comments, the program should progress further.
These commands will need to be run by anyone developing on Windows, and who has checked out the code before my change is applied.

2) This doesn't fix everything, there is still an issue with `sample_input_files/human/trials/1/data.csv` that gives the following error
```python
$ python -m simple_network_sim.sampleUseOfModel
[2020-07-08 17:27:11,315] [simple_network_sim.__main__] [INFO] Parameters
        data_pipeline_config=config.yaml
        debug=False
        logfile=None
        quiet=False
        time=200
        use_movement_multipliers=False
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/storage/local/src/git/simple_network_sim/simple_network_sim/sampleUseOfModel.py", line 209, in <module>
    main(sys.argv[1:])
  File "/storage/local/src/git/simple_network_sim/simple_network_sim/sampleUseOfModel.py", line 35, in main
    store.read_table("human/trials"),
  File "/storage/local/src/git/simple_network_sim/simple_network_sim/data.py", line 9, in read_table
    with TextIOWrapper(self.open_for_read(data_product=data_product, extension="csv")) as csv_file:
  File "/home/enigma/.virtualenvs/simple_network_sim/lib/python3.7/site-packages/data_pipeline_api/file_api.py", line 116, in open_for_read
    verify_hash=self.fail_on_hash_mismatch,
  File "/home/enigma/.virtualenvs/simple_network_sim/lib/python3.7/site-packages/data_pipeline_api/file_api.py", line 86, in _record_access
    ).format(**access_metadata)
ValueError: calculated hash fb411a3ecc96941626944dad611244cb31349d23 != verified hash 33d97bfd0e2c92f5002a9d1cd62a7a822fd57d0f
```

This occurs on Linux as well as on Windows, with the same error on both, so I think this is more that the file store is corrupt, but I'd ask someone else to verify at least.

3) This highlights the fact that these hashes not matching are not being tested by our CI, so an issue should probably be raised for that particular problem.

**Comment by bobturneruk** [comment] 2020-07-14 14:37
I've followed the instructions, thanks @WPettersson , and all tests pass. Regarding the lack of CI testing for Windows there is now this issue. https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/545

**Closed** 2020-07-21 16:11 UTC
Labels: Simple Network Sim, Windows 10, data pipeline api
