### ISSUE TITLE
Move TOML input file functions out of analysis.cc

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#557] opened 2020-07-06 17:04 UTC

**Comment by rwj11** [comment] 2020-07-14 12:32
See Herb Sutter's series of GoTW articles on implementing the Pimpl (pointer-to-implementation) idiom in modern C++ https://herbsutter.com/2013/08/12/gotw-7a-minimizing-compile-time-dependencies-part-1/

**Comment by ianhinder** [comment] 2020-07-14 13:15
My intention wasn't necessarily to avoid having the compile-time dependency, just to make the code more modular and not clutter the main module with the TOML stuff.  There is a large amount of parameter parsing logic in there now, and given the scoping issues relating to where all the parameters are "sent", I think that big block has to stay there.  But the function definitions can be moved out.

**Comment by rwj11** [comment] 2020-07-14 13:51
There is the issue is that anything that's in `main` can't be unit tested.  The toml code also looks like it needs quite a lot of boilerplate to get anything done -- you need to type a parameter's name 3 times to read it, not counting where it is put.
I wasn't sure if the motivation was in part to avoid needing to use `-O0` on this code: this seems like it may be a common issue with templated parser libraries, cf e.g. https://stackoverflow.com/questions/5504997/minimizing-boostspirit-compile-times
> The problem is that compile takes for ever! It takes about ten minutes and requires almost a gigabyte of memory. The original flex parser compiled in a few seconds.

**Comment by ianhinder** [comment] 2020-07-14 19:19
Yes, we could certainly move it out of main. Yes, I don't like the amount of boilerplate.  When I implemented the TOML stuff, I was quite constrained by needing to maintain precise backward compatibility with the existing argv parser code, and it ended up being a bit ugly, but I ran out of steam for refactoring it. The way it handles defaults is also not great.  

Regarding the compile time: yes, it seems to be a common problem with templated anything. Especially the header-only libraries, where you often end up compiling everything every time.  The original interface I added didn't really expose the TOML nature of the parameters at all, as I was only presenting a flat list of strings, ints, bools and doubles. However, Chris needed more structure in the parameters, so now they can be arbitrary TOML values, more or less, so the TOML needs to be exposed.

**Comment by ianhinder** [comment] 2020-07-15 18:20
Note: there is a lot of TOML reading code in model.cc as well. It's not clear if it makes sense to try to create an abstraction layer for everything in TOML that we use.  We might want to split out just the TOML parts into modeltoml.cc or something. But perhaps this is not a very high priority.

**Comment by rwj11** [comment] 2020-08-11 16:00
Addressed by https://github.com/ScottishCovidResponse/BEEPmbp/pull/21

**Closed by rwj11** 2020-08-11 16:00 UTC
Labels: BEEPmbp
