### ISSUE TITLE
test_run_seeded fails (windows setup)

### ISSUE THREAD

**Issue by may1066** [ScottishCovidResponse/SCRCIssueTracking#441] opened 2020-06-11 18:23 UTC
Run on windows 10 in a conda enviroment initialised using environment.yml (and miniconda).
Output:
>  AssertionError: assert '2ebd6681a6f0...e79cfd78df678' == '697ce151437d...a9ea8edb37049'
>    \- 697ce151437d64264a9a9ea8edb37049
>    \+ 2ebd6681a6f0c0a954ae79cfd78df678

**Comment by bobturneruk** [comment] 2020-06-22 08:13
@FiodorG , @aflag does this realted to https://github.com/ScottishCovidResponse/simple_network_sim/pull/64 ?

**Comment by bobturneruk** [comment] 2020-07-02 10:45
If I use `git status --ignored` to find temporary files not part of the repository and delete these, all tests pass on Windows. I'm not 100% sure why this would be needed, but it resolves the issue. I suggest that we note here if it recurs.

**Comment by WPettersson** [comment] 2020-07-02 19:08
If testing might leave existing files around, and those files might later cause incorrect results, we should probably do something about it. Otherwise someone might run tests, have everything pass, and then run the code on real data and get wrong results. Options I see are to either ensure that no files are left around, or that if files are left around, they either don't cause any problems or they at least show some sort of warning. Ideally, both, to be honest.

**Comment by bobturneruk** [comment] 2020-07-03 08:05
I had assumed that it was a conflict with files output by a previous version of the software. I agree it's a bit concerning. Can we / should we account for other stuff people might have in their folders on disk? Should we make sure we're not leaving stuff around going forwards? This may relate to https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/501 - but needs some investigation.

**Comment by WPettersson** [comment] 2020-07-03 08:15
Leaving stuff around is not desirable, but I think the bigger issue is incorrect output if other files are around. As you say, we cannot know what things other people might have in their folders. However, I'm still not even sure how these errors are actually occurring, it does  seem to be related to Windows, and I don't have a Windows machine here for testing.

**Comment by bobturneruk** [comment] 2020-07-03 08:18
Thanks again for the input. I am also discomfited by not knowing what was going wrong (a fix is fine, but unsettling if one doesn't know the cause). We'll need to leave this open until someone has time to investigate. This may be related https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/545

**Comment by bobturneruk** [comment] 2020-07-03 08:18
I guess it could be that it was a previous version leaving stuff around and this is now resolved. Speculation. Need to confirm.

**Comment by bobturneruk** [comment] 2020-07-22 09:35
This has been resolved by multiple PRs.

**Closed by bobturneruk** 2020-07-22 09:35 UTC
Labels: Bug, Simple Network Sim
