### ISSUE TITLE
Forward prediction mode requires observational data

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#733] opened 2020-08-14 10:39 UTC
The observational data in the `scot_data.csv` and `scot_deaths.csv` files are used in inference mode, to compare the model's predicted cases/deaths with actual cases/deaths. The data in these files are not required in forward prediction mode.

When starting a run in forward prediction mode, the run terminates with an error if the above files are not present. The code needs to be updated to remove this unnecessary dependency.

**Comment by kzscisoft** [comment] 2020-08-25 13:51
Closing issue as `scot_data` is required for all model runs as part of the setup, this is not a bug.

**Closed as completed by kzscisoft** 2020-08-25 13:51 UTC
Labels: Bug, Covid19_EERAModel
