### ISSUE TITLE
Read time-dependent dampening factor for the age-mixing within-population contacts and then apply to the within-population contacts (and thus eventually to the resulting infection).  This is similar to what we've done with the movement dampening.

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#325] opened 2020-05-30 14:53 UTC

**Comment by aflag** [comment] 2020-06-04 08:56
Duplicate of #287

**Closed by aflag** 2020-06-04 08:56 UTC
Labels: Simple Network Sim
